---
title: Mobywhale Chan.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Fiona Chan
baseurl: 
paginate: 5
paginate_path: page:num
markdown: kramdown
auto: true
permalink: "/:year/:month/:title.html"
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- node_modules
- sass
- lib
- config.rb
- config
- Rakefile
- Rakefile.rb
- tmp
- "*.sublime-project"
- "*.sublime-workspace"
